import { Spectral } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/navbar";
import TopNav from "@/components/Shared/topNav";
import GoldenEraFooter from "@/components/Shared/Footer";
import Providers from "./provider";

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-spectral",
  display: "swap",
});

export const metadata = {
  title: "Golden Era",
  description: "Generated by create next app",
  icons: {
    icon: "/goldeneralogo.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spectral.variable}`}>
        <Providers>
          <TopNav />
          <Navbar />
          {children}
          <GoldenEraFooter />
        </Providers>
      </body>
    </html>
  );
}

