import { Spectral } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/Shared/navbar";
import TopNav from "@/components/Shared/topNav";

const spectral = Spectral({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-spectral',
  display: 'swap',
});


export const metadata = {
  title: "Golden Era",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spectral.variable}`}
      >
        <TopNav />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
